# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    insecure-external-code-execution: deny
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "11:00" #default if 5AM UTC
      timezone: "America/Los_Angeles"
    versioning-strategy: auto
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ðŸ†™ - npm prod"
      prefix-development: "ðŸ†™ - pip dev"
      include: "scope"
    reviewers:
      - "megamanics"
    assignees:
      - "megamanics"
    allow:
      - dependency-type: "all"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
      
  - package-ecosystem: 'github-actions'
    insecure-external-code-execution: deny
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "12:00" #default if 5AM UTC
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ðŸ†™ - Action prod"
      prefix-development: "ðŸ†™ - Action dev"
      include: "scope"
    assignees:
      - "megamanics"
    allow:
      - dependency-type: "all"
    labels:
      - "actions"
      - "dependencies"
      - "dependabot"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
